# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Navtor::FMState; end
module Navtor::Utils::InvalidParameter; end
module Navtor::Value::HashDiff; end
